import type { Metadata } from "next";
import { Barriecito, Outfit } from "next/font/google";
import "./globals.css";
import { MusicProvider } from "./components/MusicProvider";
import MusicControls from "./components/MusicControls";
import { AnswerProvider } from "@/context/AnswerContext";

const barriecitoSans = Barriecito({
  weight: "400",
  variable: "--font-barriecito-sans",
  subsets: ["latin"],
});

const outfitSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Valentine CHEI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barriecitoSans.variable} ${outfitSans.variable} antialiased`}
      >
        <AnswerProvider>
          <MusicProvider>
            {children} <MusicControls />
          </MusicProvider>
        </AnswerProvider>
      </body>
    </html>
  );
}
